## NUMPY
#### NumPy is a Fundamental Package for scientific computing in Python. It is a Python Library that provides a Multi-Dimensional array object and various derived objects such as Masked Arrays or Matrices and an assortment of routines for fast operations on Arrays including Mathematical, Logical, Shape Manipulation, Sorting, Selecting, I/O, Discrete Fourier Transforms, Basic Linear Algebra, Statistical Operations, Random Simulation, etc.
#### this package is the ndimensional Array object

#### Numpy Arrays vs Python Sequences 

#### Numpy Arrays fixed size, unlike python lists which grow dynamically. changing the size of ndim array will create new array and delete original

#### The elements in numpy array are required to be of the same data type same size and meomry 

#### numoy arrays facilitate advanced mathematical and othe type of operation on large number of data , typically such operations are executed efficiently with less code than is possible using pythons built in sequences.


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [12]:
numpy_array=np.array([1,2,3,4,5])

In [13]:
numpy_array

array([1, 2, 3, 4, 5])

In [14]:
type(numpy_array)

numpy.ndarray

In [8]:
twod=np.array([[1,2,3],[4,5,6]])

In [9]:
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
threeD = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [11]:
threeD

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### np.array helps to create Multidimensional Arrays

### dtype = used for deciding size for array it can 32,64,int,bool,float

In [16]:
np.array([1,2,3,4,5],dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### arange functions helps us out with providing the values over a certain range

In [24]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
arange_data = np.arange(1,17)

In [28]:
arange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### reshape -> it used to shape the arrray 

### ones() function = each and every single value = 1 in a matrix 
### zeros() = same but value 0
### random() = it helps us out with generating any random values from 0to1 inside our matrix

In [29]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.zeros((4,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [31]:
np.random.random((3,4))

array([[0.77106601, 0.04218833, 0.12079675, 0.17765454],
       [0.26179055, 0.55729137, 0.06329491, 0.29451418],
       [0.4636896 , 0.9357054 , 0.88356212, 0.44472767]])

## identity dunction() = square matrix i.e. rows=column and diagonal values will be 1 and other will be zero


In [37]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### linspace()-> it makes sure that every value with the given range is going to have similar distance from each other

In [17]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## Most IMP Attributes

#### ndim-> n distance

In [18]:
arr = np.array([1,2,3])

In [19]:
arr

array([1, 2, 3])

In [20]:
arr.ndim

1

In [23]:
arrayy = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [24]:
arrayy.ndim

3

In [26]:
np.array([[1,2],[3,4]]).ndim

2

#### shape -> it provides the idea about the rows , columns in our dataset or in array

In [27]:
aa=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [28]:
aa

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
aa.shape

(3, 3)

#### size -> total number of elements present inside our dataset

In [31]:
array_elements=np.arange(5,57)

In [32]:
array_elements

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56])

In [33]:
array_elements.size

52

#### itemsize -> provides with the idea about the size ofa unique element inside our array in bytes

In [39]:
np.array([[[1,2],[3,4],[5,6]]],dtype=np.int32).itemsize

4

#### dtype -> provides the idea about the type of every item inside array

In [41]:
np.array([[1,2,3],[4,5,6]]).dtype

dtype('int64')