## NUMPY
#### NumPy is a Fundamental Package for scientific computing in Python. It is a Python Library that provides a Multi-Dimensional array object and various derived objects such as Masked Arrays or Matrices and an assortment of routines for fast operations on Arrays including Mathematical, Logical, Shape Manipulation, Sorting, Selecting, I/O, Discrete Fourier Transforms, Basic Linear Algebra, Statistical Operations, Random Simulation, etc.
#### this package is the ndimensional Array object

#### Numpy Arrays vs Python Sequences 

#### Numpy Arrays fixed size, unlike python lists which grow dynamically. changing the size of ndim array will create new array and delete original

#### The elements in numpy array are required to be of the same data type same size and meomry 

#### numoy arrays facilitate advanced mathematical and othe type of operation on large number of data , typically such operations are executed efficiently with less code than is possible using pythons built in sequences.


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [12]:
numpy_array=np.array([1,2,3,4,5])

In [13]:
numpy_array

array([1, 2, 3, 4, 5])

In [14]:
type(numpy_array)

numpy.ndarray

In [8]:
twod=np.array([[1,2,3],[4,5,6]])

In [9]:
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
threeD = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [11]:
threeD

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### np.array helps to create Multidimensional Arrays

### dtype = used for deciding size for array it can 32,64,int,bool,float

In [16]:
np.array([1,2,3,4,5],dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### arange functions helps us out with providing the values over a certain range

In [24]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
arange_data = np.arange(1,17)

In [28]:
arange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### reshape -> it used to shape the arrray 

### ones() function = each and every single value = 1 in a matrix 
### zeros() = same but value 0
### random() = it helps us out with generating any random values from 0to1 inside our matrix

In [29]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.zeros((4,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [31]:
np.random.random((3,4))

array([[0.77106601, 0.04218833, 0.12079675, 0.17765454],
       [0.26179055, 0.55729137, 0.06329491, 0.29451418],
       [0.4636896 , 0.9357054 , 0.88356212, 0.44472767]])

## identity function() = square matrix i.e. rows=column and diagonal values will be 1 and other will be zero


In [37]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### linspace()-> it makes sure that every value with the given range is going to have similar distance from each other

In [17]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## Most IMP Attributes

#### ndim-> n distance

In [18]:
arr = np.array([1,2,3])

In [19]:
arr

array([1, 2, 3])

In [20]:
arr.ndim

1

In [23]:
arrayy = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [24]:
arrayy.ndim

3

In [26]:
np.array([[1,2],[3,4]]).ndim

2

#### shape -> it provides the idea about the rows , columns in our dataset or in array

In [27]:
aa=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [28]:
aa

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
aa.shape

(3, 3)

#### size -> total number of elements present inside our dataset

In [31]:
array_elements=np.arange(5,57)

In [32]:
array_elements

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56])

In [33]:
array_elements.size

52

#### itemsize -> provides with the idea about the size ofa unique element inside our array in bytes

In [39]:
np.array([[[1,2],[3,4],[5,6]]],dtype=np.int32).itemsize

4

#### dtype -> provides the idea about the type of every item inside array

In [41]:
np.array([[1,2,3],[4,5,6]]).dtype

dtype('int64')

#### astype() -> heelps us figure out the datatype of a column of dataset in pandas and it will be used in numpy as well for getting data type change of over al arrat 

In [19]:
array = np.arange(1,10).reshape(3,3)

In [20]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
array=array.astype('float64')

In [23]:
type(array)

numpy.ndarray

In [24]:
array.dtype

dtype('float64')

### Mathematical Operations in Numpy

#### Scalar operation -> A scalar value operation can be done with the array or a numeric value (eg. 1,4)

In [32]:
array=np.random.random((3,3))*100

In [33]:
array=np.round(array)

In [34]:
array = array.astype('int32')

In [35]:
array

array([[99,  1, 18],
       [57, 41, 92],
       [98, 56,  6]], dtype=int32)

#### Scalar operations with our matix or arrray

In [44]:

array+2

array([[101,   3,  20],
       [ 59,  43,  94],
       [100,  58,   8]], dtype=int32)

In [37]:
array-9

array([[90, -8,  9],
       [48, 32, 83],
       [89, 47, -3]], dtype=int32)

In [39]:
array*6

array([[594,   6, 108],
       [342, 246, 552],
       [588, 336,  36]], dtype=int32)

In [40]:
array/2

array([[49.5,  0.5,  9. ],
       [28.5, 20.5, 46. ],
       [49. , 28. ,  3. ]])

In [43]:
array>60

array([[ True, False, False],
       [False, False,  True],
       [ True, False, False]])

#### Vector Operations -> operations will be in between the given numbe rof matrices

In [45]:
arr_1 = np.arange(1,17).reshape(4,4)

In [54]:
arr_2 = np.arange(17,33).reshape(4,4)

In [55]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [56]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [57]:
arr_1+arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [58]:
arr_1*arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

#### imp functions in numpy and ML

#### max()-> max value inside a matrix or array i.e np.max(array)

In [60]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
max_value=np.max(arr_1)

In [63]:
max_value

np.int64(16)

In [66]:
aray_data=np.round(np.random.random((4,4))*100).astype('int32')

In [67]:
aray_data

array([[17, 98, 58, 12],
       [73, 57, 45, 16],
       [ 9, 84, 15, 25],
       [ 1, 96,  0,  9]], dtype=int32)

#### axis -> it provides the idea bout any operation value indside a row or colummn or we can get specific value row wise or column wise
#### axis=0 --column wise
#### axis=1 --row wise operation

In [69]:
np.max(aray_data,axis=0)

array([73, 98, 58, 25], dtype=int32)

In [70]:
np.max(aray_data,axis=1)

array([98, 73, 84, 96], dtype=int32)

#### min() -> used for calculating minimum value from the matrix or array i.e. np.min()

In [71]:
aray_data

array([[17, 98, 58, 12],
       [73, 57, 45, 16],
       [ 9, 84, 15, 25],
       [ 1, 96,  0,  9]], dtype=int32)

In [72]:
np.min(aray_data)

np.int32(0)

In [73]:
np.min(aray_data,axis=0)

array([ 1, 57,  0,  9], dtype=int32)

In [74]:
np.min(aray_data,axis=1)

array([12, 16,  9,  0], dtype=int32)

In [75]:
array = np.arange(1,10)

In [76]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.min(array)

np.int64(1)

#### sum() -> calculates sum of all the values in given matrix i.e. np.sum()

In [78]:
aray_data

array([[17, 98, 58, 12],
       [73, 57, 45, 16],
       [ 9, 84, 15, 25],
       [ 1, 96,  0,  9]], dtype=int32)

In [79]:
np.sum(aray_data)

np.int64(615)

In [80]:
np.sum(aray_data,axis=1)

array([185, 191, 133, 106])

In [81]:
np.sum(aray_data,axis=0)

array([100, 335, 118,  62])

#### product() -> calculates the product of all values inside a matrix i.e. np.prod()

In [88]:
np.prod(aray_data)

np.int64(0)

In [89]:
np.prod(aray_data,axis=1)

array([1159536, 2995920,  283500,       0])

In [91]:
np.prod(aray_data,axis=0)


array([   11169, 45045504,        0,    43200])

#### Statistical Function in Numpy

#### mean() -> mean of all values inside array or matrix i.e. np.mean

In [94]:
aray_data

array([[17, 98, 58, 12],
       [73, 57, 45, 16],
       [ 9, 84, 15, 25],
       [ 1, 96,  0,  9]], dtype=int32)

In [95]:
np.mean(aray_data)

np.float64(38.4375)

In [96]:
np.mean(aray_data,axis=0)

array([25.  , 83.75, 29.5 , 15.5 ])

#### std() -> standard deviation of all values of the matricx or array

In [97]:
np.std(aray_data)

np.float64(33.45326731053336)

#### median() -> calculate the median of all values in the array or matrix i.e. np.median

In [98]:
aray_data

array([[17, 98, 58, 12],
       [73, 57, 45, 16],
       [ 9, 84, 15, 25],
       [ 1, 96,  0,  9]], dtype=int32)

In [99]:
np.median(aray_data)

np.float64(21.0)

#### var() -> variance of all values inside the array or matrix i.e np.var(0)

In [100]:
np.var(aray_data)

np.float64(1119.12109375)

#### Trignometric Functions 
#### np.sin,cos,tan

In [101]:
np.sin(45)

np.float64(0.8509035245341184)

#### dot product -> remember the two matrix should be 3,4 and 4,3 i.e np.dot(matrix1,matrix2)

In [109]:
matrix_1=np.round(np.random.random((3,4))*100).astype('int32')
matrix_2=np.round(np.random.random((4,3))*100).astype('int32')

In [110]:
matrix_1

array([[82, 56,  9, 29],
       [63, 62,  3, 66],
       [93, 30, 83, 83]], dtype=int32)

In [111]:
matrix_2

array([[42, 61, 90],
       [ 6, 84, 34],
       [75, 38, 38],
       [35, 26, 52]], dtype=int32)

In [112]:
np.dot(matrix_1,matrix_2)

array([[ 5470, 10802, 11134],
       [ 5553, 10881, 11324],
       [13216, 13505, 16860]], dtype=int32)

#### round-ceil(1.3=2|1.6=2)-floor(1.3=1|1.6=1)

#### transpose -> calculates the transpose of the given matrix i.e. np.transpose() or arr.T
#### Transpose -> (i,j) -> (j,i) i.e ->(3,4) - T - (4,3)

In [5]:
array = np.arange(1,13).reshape(3,4)

In [6]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

#### ravel() -> ravel -> np.ravel -> convert nd array into  1d array

In [8]:
array.ndim

2

In [9]:
np.ravel(array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### Indexing and Slicing in numpy

#### Indexing -> lists[,size-1]->To have the access over the values

In [11]:
array = np.round(np.random.random((5,5))*100).astype('int32')

In [12]:
array

array([[ 87,   2,  16,  82,  77],
       [ 97,  75,   7,  93, 100],
       [ 17,  61,  39,   6,  80],
       [ 71,  15,  35,  37,  12],
       [ 64,  48,  87,  35,  74]], dtype=int32)

In [13]:
array_one=np.arange(1,10)

In [14]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array_one[6]

np.int64(7)

In [16]:
array

array([[ 87,   2,  16,  82,  77],
       [ 97,  75,   7,  93, 100],
       [ 17,  61,  39,   6,  80],
       [ 71,  15,  35,  37,  12],
       [ 64,  48,  87,  35,  74]], dtype=int32)

In [17]:
array_one[8]

np.int64(9)

In [19]:
array[4,4]

np.int32(74)

#### indexing 2d array -> [row,column]
#### indexing 3d array -> [z-axis,x-axis,y-axis]

In [20]:
array_three = np.arange(1,9).reshape(2,2,2)

In [21]:
array_three

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
array_three[1,0,1]

np.int64(6)

#### Slicing -> similar approach just link the list [:]
#### 2D Array -> [row_1:row_2,col_1:col_2]

In [25]:
array

array([[ 87,   2,  16,  82,  77],
       [ 97,  75,   7,  93, 100],
       [ 17,  61,  39,   6,  80],
       [ 71,  15,  35,  37,  12],
       [ 64,  48,  87,  35,  74]], dtype=int32)

In [23]:
array[:,2]

array([16,  7, 39, 35, 87], dtype=int32)

In [26]:
array[0,:]

array([87,  2, 16, 82, 77], dtype=int32)

In [27]:
array[2:4,3:5]

array([[ 6, 80],
       [37, 12]], dtype=int32)

In [4]:
array=np.arange(1,10)

In [5]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
for i in array:
    print(i)

1
2
3
4
5
6
7
8
9


In [9]:
array=np.arange(1,28).reshape(3,3,3)

In [10]:
for i in array:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


#### Stackin and Splitting| size of arrays must be same

#### stacking -> joining the ararays together
#### horizontal stacking -> row by row joining is done -> hstack()
#### vertical stacking -> column by column join is done -> vstack()

In [13]:
array_1 = np.arange(1,13).reshape(3,4)

In [14]:
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
array_2 = np.arange(13,25).reshape(3,4)

In [16]:
array_2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [19]:
horizontal_array = np.hstack((array_1,array_2))

In [20]:
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [22]:
vertical_array = np.vstack((array_1,array_2))

In [23]:
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

#### horizontal split -> np.hsplit(array,number of parts you want your array to be splitted at)
#### vertical split -> np.vsplit(array,number of parts)

In [24]:
np.hsplit(vertical_array,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [25]:
np.vsplit(horizontal_array,3)

[array([[ 1,  2,  3,  4, 13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8, 17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12, 21, 22, 23, 24]])]